name: Hassfest Validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hassfest Action
        uses: home-assistant/actions/hassfest@master
